# Generated by Django 5.0.1 on 2024-01-28 00:27

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AboutWork",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.CharField(max_length=50, verbose_name="Картинка")),
                ("title", models.CharField(max_length=50, verbose_name="Название")),
                ("text", models.TextField(verbose_name="Text")),
            ],
        ),
    ]
